FROM ubuntu:20.04 AS base

COPY sources.list /etc/apt/
ENV TZ=Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone


#######################
## Install libjudger ##
#######################
FROM base AS build-judger

WORKDIR /build
COPY ./libjudger ./

RUN apt-get update && apt-get -y install libseccomp-dev cmake
RUN cmake CMakeLists.txt && make && make install


#######################
## Install go server ##
#######################
FROM golang:1.19-alpine AS build-server

WORKDIR /build

COPY . .
RUN go mod vendor
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/server


####################
## for production ##
####################
FROM base AS production

WORKDIR /app
RUN mkdir -p sandbox/policy \
  && mkdir sandbox/results\
  && mkdir -p sandbox/logs/run \
  && mkdir -p sandbox/logs/compile

COPY libjudger/java_policy sandbox/policy/

RUN buildDeps='software-properties-common curl' \
  && apt-get update && apt-get install -y $buildDeps \
  && add-apt-repository ppa:deadsnakes/ppa \
  && curl -sL https://deb.nodesource.com/setup_16.x | bash -E - \
  && apt-get update && apt-get install -y \
  gcc \
  g++ \
  nodejs \
  python3.10 \
  pypy3 \
  openjdk-17-jdk \
  && apt-get purge -y --auto-remove $buildDeps \
  && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY --from=build-judger /build/output/libjudger.so ./sandbox/
COPY --from=build-server /build/bin/server .

ENV APP_ENV=production
COPY ./scripts/entrypoint.sh /app/
ENTRYPOINT [ "sh", "./entrypoint.sh" ]
