version: "3"
services:
  judge-manager-deploy:
    container_name: judge-manager
    image: jm:dev
    stdin_open: true
    tty: true
    environment:
      - "TESTCASE_SERVER_URL=http://host.docker.internal:3000/testcase/problem/"
      - "TESTCASE_SERVER_AUTH_TOKEN=AUTH_TOKEN"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
    cpuset: "0,1,2"

  redis:
    container_name: redis
    image: redis:alpine
    ports: 
      - 6379:6379
