version: "3"
services:
  judge-manager-deploy:
    container_name: judge-manager-dev
    image: coc0a25/judge-manager:dev
    stdin_open: true
    tty: true
    environment:
      - TESTCASE_SERVER_URL=http://host.docker.internal:3000/testcase/problem/
      - TESTCASE_SERVER_AUTH_TOKEN=AUTH_TOKEN
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_DEFAULT_USER=skku
      - RABBITMQ_DEFAULT_PASS=1234
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    cpuset: "0,1,2"

  redis:
    container_name: redis-dev
    image: redis:alpine
    ports: 
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-dev
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_ERLANG_COOKIE=RabbitMQ-My-Cookies
      - RABBITMQ_DEFAULT_USER=skku
      - RABBITMQ_DEFAULT_PASS=1234
