version: "3"
services:
  iris-dev:
    container_name: iris-dev
    build:
      context: ..
      dockerfile: Dockerfile-dev
    depends_on:
      - rabbitmq-dev
    stdin_open: true
    tty: true
    volumes:
      - ..:/app/src:cached
    environment:
      TESTCASE_SERVER_URL: http://testcase-server-dev:30000/problem/:id/testcase
      TESTCASE_SERVER_URL_PLACEHOLDER: :id
      TESTCASE_SERVER_AUTH_HEADER: Authorization
      TESTCASE_SERVER_AUTH_TOKEN: iris-token
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_CONSUMER_CONNECTION_NAME: ${RABBITMQ_CONSUMER_CONNECTION_NAME}
      RABBITMQ_CONSUMER_QUEUE_NAME: ${JUDGE_SUBMISSION_QUEUE_NAME}
      RABBITMQ_CONSUMER_TAG: ${RABBITMQ_CONSUMER_TAG}
      RABBITMQ_PRODUCER_CONNECTION_NAME: ${RABBITMQ_PRODUCER_CONNECTION_NAME}
      RABBITMQ_PRODUCER_EXCHANGE_NAME: ${JUDGE_EXCHANGE_NAME}
      RABBITMQ_PRODUCER_ROUTING_KEY: ${JUDGE_RESULT_ROUTING_KEY}

  testcase-server-dev:
    container_name: testcase-server-dev
    build:
      context: ../tests/testcase-server
      dockerfile: Dockerfile
    stdin_open: true
    tty: true

  redis-dev:
    container_name: ${REDIS_HOST}
    image: redis:alpine

  setup-dev:
    image: python:3.8-alpine
    depends_on:
      - rabbitmq-dev
    volumes:
      - ../scripts/rabbitmq-setup.sh:/setup.sh
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      JUDGE_EXCHANGE_NAME: ${JUDGE_EXCHANGE_NAME}
      JUDGE_SUBMISSION_QUEUE_NAME: ${JUDGE_SUBMISSION_QUEUE_NAME}
      JUDGE_SUBMISSION_ROUTING_KEY: ${JUDGE_SUBMISSION_ROUTING_KEY}
      JUDGE_RESULT_QUEUE_NAME: ${JUDGE_RESULT_QUEUE_NAME}
      JUDGE_RESULT_ROUTING_KEY: ${JUDGE_RESULT_ROUTING_KEY}
    entrypoint:
      - /setup.sh

  rabbitmq-dev:
    image: rabbitmq:3-management-alpine
    container_name: ${RABBITMQ_HOST}
    ports:
      - ${RABBITMQ_ADMIN_PORT}:15672
    environment:
      RABBITMQ_ERLANG_COOKIE: RabbitMQ-My-Cookies
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
